apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: pgadmin
  namespace: ns
spec:
  ports:
  - nodePort: 31928
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: pgadmin
  type: NodePort
status:
  loadBalancer: {}
