apiVersion: v1
data:
  JWT_SECRET: YOUR SECRET IN BASE64 ENCODED
  MAILER_PASS: YOUR SECRET IN BASE64 ENCODED
  MAILER_USER: YOUR SECRET IN BASE64 ENCODED
kind: Secret
metadata:
  creationTimestamp: null
  name: server-secret
  namespace: ns
