apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-pv-db-inspector
  name: pod-pv-db-inspector
  namespace: ns
spec:
  restartPolicy: Never
  containers:
  - image: busybox
    name: pod-pv-db-inspector
    command: ["/bin/sh", "-c", "ls -lrt /mnt/db/data""]
    volumeMounts:
    - mountPath: /mnt/db/data"
      name: pv-db-storage
    resources: {}
  volumes:
  - name: pv-db-storage
    persistentVolumeClaim:
      claimName: pv-db-claim  
status: {}
