apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-server
  labels:
    type: local
spec:
  storageClassName: manual
  claimRef:
    name: pv-server-claim
    namespace: ns
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/image/data"
