apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-server-claim
  namespace: ns
spec:
  storageClassName: manual
  volumeName: pv-server
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
