apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client
    run: client
  name: client
  namespace: ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client
        run: client
    spec:
      containers:
      - image: rest-client:0.0.1
        imagePullPolicy: Never
        name: client
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/nginx/html/config.js
          name: client-config-file
          subPath: config.js
        resources: 
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 1000m
      volumes:
      - configMap:
          name: client-configmap
          defaultMode: 420
          optional: true
        name: client-config-file
status: {}
