apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client
    run: client
  name: client
  namespace: ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client
        run: client
    spec:
      containers:
      - image: rest-client:0.0.1
        imagePullPolicy: Never
        name: client
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_SERVER_ADDR
          valueFrom: 
            configMapKeyRef:
              name: client-configmap
              key: REACT_APP_BACKEND_SERVER_ADDR
        resources: 
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 1000m
status: {}
