apiVersion: v1
kind: Secret
metadata:
  name: client-secret
  namespace: ns
type: Opaque # Or kubernetes.io/tls if strictly for TLS, but Opaque allows combining
data:
  # TLS certificate and key (base64 encoded from files)
  # Ensure 'tls.crt' and 'tls.key' are the actual filenames of your certificate and private key files
  # and their content is base64 encoded.
  # For example:
  # echo -n "$(cat tls.crt | base64 -w 0)" > tls_crt_encoded.txt
  # echo -n "$(cat tls.key | base64 -w 0)" > tls_key_encoded.txt
  # Then copy the content of tls_crt_encoded.txt and tls_key_encoded.txt here.
  tls.crt: <base64_encoded_content_of_tls.crt>
  tls.key: <base64_encoded_content_of_tls.key>
  dhparam.pem: <base64_encoded_content_of_dhparam.pem>

  # Username and password (base64 encoded)
  # For example:
  # echo -n "myuser" | base64 -w 0
  # echo -n "mypassword" | base64 -w 0
  username: <base64_encoded_username>
  password: <base64_encoded_password>
  REACT_APP_SECRET: YOUR SECRET IN BASE64 ENCODED
