apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client
    run: client
  name: client
  namespace: ns
spec:
  ports:
  - nodePort: 31602
    port: 3000
    protocol: TCP
    targetPort: 3000
  - nodePort: 31443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: client
  type: NodePort
status:
  loadBalancer: {}
