apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres
    run: postgres
  name: postgres
  namespace: ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
        run: postgres
    spec:
      containers:
      - image: postgres:10.1
        imagePullPolicy: "IfNotPresent"
        name: postgres
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-configmap
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pv-db-storage
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 1000m
      volumes:
      - name: pv-db-storage
        persistentVolumeClaim:
          claimName: postgres-pv-db-claim
status: {}
