apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-db
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  claimRef:
    name: postgres-pv-db-claim
    namespace: ns
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/db/posgresdata"
