apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-db-claim
  namespace: ns
  labels:
    app: postgres
spec:
  storageClassName: manual
  volumeName: postgres-pv-db
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
