apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres
    run: postgres
  name: postgres
  namespace: ns
spec:
  ports:
  - nodePort: 31587
    port: 5432
  selector:
    app: postgres
  type: NodePort
status:
  loadBalancer: {}
