apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: server
    run: server
  name: server
  namespace: ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server
        run: server
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
      - image: busybox
        command: ["/bin/chown", "-R", "1000:1000", "/home/node/app/server/images"]
        securityContext:
          runAsUser: 0
          privileged: true
        imagePullPolicy: Never
        name: change-ownership-container
        volumeMounts:
        - mountPath: /home/node/app/server/images
          name: pv-image-storage
      containers:
      - image: rest-server:0.0.1
        imagePullPolicy: Never
        name: server
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /home/node/app/server/images
          name: pv-image-storage
        env:
        - name: DB_URI
          valueFrom: 
            configMapKeyRef:
              name: server-configmap
              key: DB_URI
        - name: MAILER_USER
          valueFrom: 
            secretKeyRef:
              name: server-secret
              key: MAILER_USER
        - name: MAILER_PASS
          valueFrom: 
            secretKeyRef:
              name: server-secret
              key: MAILER_PASS
        - name: MAILER_HOST
          valueFrom: 
            configMapKeyRef:
              name: server-configmap
              key: MAILER_HOST
        - name: MAILER_PORT
          valueFrom: 
            configMapKeyRef:
              name: server-configmap
              key: MAILER_PORT
        - name: JWT_SECRET
          valueFrom: 
            secretKeyRef:
              name: server-secret
              key: JWT_SECRET
        - name: JWT_TOKEN_EXPIRE
          value: "30m"
        - name: LOG_LEVEL
          value: "DEBUG"
        livenessProbe:
          httpGet:
            path: /system/healthz
            port: 8081
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /system/healthz
            port: 8081
          failureThreshold: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /system/readyz
            port: 8081
          periodSeconds: 15
        resources: 
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 1Gi
            cpu: 1000m
      volumes:
      - name: pv-image-storage
        persistentVolumeClaim:
          claimName: pv-server-claim
status: {}
